FROM rayproject/ray:latest-cpu

COPY /IDC_regular_ps50_idx5/ /IDC_regular_ps50_idx5/

RUN pip install "torch>=1.7.0+cpu" "torchvision>=0.8.1+cpu" -f https://download.pytorch.org/whl/torch_stable.html
